version: '3'

services:
    app:
        build: ./src
        container_name: app
        depends_on:
            - mongo
        volumes:
            - ./src:/app

    mongo:
        image: mongo
        restart: always
