version: '3'

services:
    checker:
        build:
            context: ./src
            dockerfile: Dockerfile-checker
        container_name: checker
        depends_on:
            - postgres
        volumes:
            - ./src:/app
        env_file: .env

    bot:
        build:
            context: ./src
            dockerfile: Dockerfile-bot
        container_name: bot
        depends_on:
            - postgres
        volumes:
            - ./src:/app
        env_file: .env

    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: admin

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
