version: '3'

services:
    app:
        build:
            context: ./src
            dockerfile: Dockerfile-service
        container_name: app
        depends_on:
            - mongo
        volumes:
            - ./src:/app
        env_file: .env

    bot:
        build:
            context: ./src
            dockerfile: Dockerfile-bot
        container_name: bot
        depends_on:
            - mongo
        volumes:
            - ./src:/app
        env_file: .env

    mongo:
        image: mongo
        restart: always

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin
